version: '3.0'

services:

  gobmanagement:
    build: src
    ports:
      - "8143:8001"
    container_name: gobmanagement
    environment:
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: management_database
      # Gatekeeper listens on port 8000 and serves as a proxy for UWSGI
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobmanagement.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      PROXY_CLIENT_ID: ${GATEKEEPER_CLIENT_ID}
      PROXY_CLIENT_SECRET: ${GATEKEEPER_CLIENT_SECRET}
      PROXY_ENCRYPTION_KEY: ${GATEKEEPER_ENCRYPTION_KEY}
      PROXY_LISTEN: ${GATEKEEPER_LISTEN}
      PROXY_UPSTREAM_URL: ${GATEKEEPER_UPSTREAM_URL}
      PROXY_DISCOVERY_URL: ${GATEKEEPER_DISCOVERY_URL}
      PROXY_REDIRECTION_URL: ${GATEKEEPER_REDIRECTION_URL}

networks:
  default:
    external:
      name: gob-network
