version: '3.0'

services:

  gobmanagement:
    build: src
    ports:
      - "8143:8000"
    container_name: gobmanagement
    environment:
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: management_database
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "gobmanagement.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1

networks:
  default:
    external:
      name: gob-network
