version: '3.7'

services:

  gobmanagement:
    container_name: gobmanagement
    build:
      context: src
      target: development
    platform: linux/amd64
    ports:
      # No OAuth2 Proxy
      - "8143:8001"
      # With oauth2-proxy
      #   Set cookie_secure in oauth2-proxy.cfg to false
      #   Uncomment UWSGI_ATTACH_DAEMON2
      # - "8143:8000"
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      GOB_SHARED_DIR: /app/shared
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: management_database
      # Oauth2 proxy listens on port 8000 and serves as a proxy for UWSGI
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobmanagement.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: "0"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_PROCESSES: "1"
      UWGSI_SHOW_CONFIG: "1"
      UWSGI_LAZY_APPS: "1"
      UWSGI_HTTP_WEBSOCKETS: "1"
      UWSGI_BUFFER_SIZE: "32768"
      # UWSGI_ATTACH_DAEMON2: "cmd=./oauth2-proxy --config oauth2-proxy.cfg,freq=3,control=true,stopsignal=15"
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_NEED_APP: "1"

      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}
    volumes:
      - gob-volume:/app/shared
      - ./src/gobmanagement:/app/gobmanagement
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core

volumes:
  gob-volume:
    external: true

networks:
  default:
    name: gob-network
    external: true
