FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Install gobmanagement service in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt
RUN rm -rf /app/src/gobcore/tests

# Copy gobmanagement module
COPY gobmanagement gobmanagement

# Build
COPY build.sh build.sh
RUN ./build.sh

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY .coveragerc .coveragerc
COPY test.sh test.sh

# Copy jenkins files
COPY .jenkins /.jenkins
